# Generated by Django 4.2.27 on 2026-01-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'DHCP Address', 'verbose_name_plural': 'IP Addresses'},
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('dhcp', 'DHCP'), ('static', 'Static'), ('available', 'Available (Static Pool)'), ('reserved', 'Reserved (Static In Use)')], default='dhcp', max_length=20),
        ),
    ]
