# Generated by Django 4.2.27 on 2026-01-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_alter_ipaddress_options_alter_ipaddress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('dhcp', 'DHCP'), ('available', 'Available (Static Pool)'), ('reserved', 'Reserved (Static In Use)')], default='dhcp', max_length=20),
        ),
    ]
